services:
  - type: web
    name: anti-drug-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push --accept-data-loss && node prisma/seed.js && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: anti-drug-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: JWT_SECRET
        value: antidrug_club_secret_key_2026_secure
      - key: ADMIN_USERNAME
        value: admin_login
      - key: ADMIN_PASSWORD
        value: admin@login.123

databases:
  - name: anti-drug-db
    plan: free
    databaseName: antidrugquiz
    user: antidruguser
